version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4001:3000"
    volumes:
      - /apps/node_modules
      - .:/apps
    restart: always
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /apps/node_modules
      - .:/apps
    command: ["npm", "run", "test"]
